/**
 * JPEG 1200×630 (≤300 KB, quality ~82, cover centrado) generated from
 * the current production og:image / portada of each sitemap URL.
 * Do not hand-edit the maps; regenerate with scripts/generate-og-jpegs
 * (the one-off lives next to the audit).
 */
export const OG_JPEG_SIZE = { width: 1200, height: 630 } as const;

export const OG_JPEG_BY_PATH = {
  "/politica-de-privacidad": "/images/og/home.jpg",
  "/agencia-shopify": "/images/og/agencia-shopify.jpg",
  "/contactar-agencia-de-marketing-digital": "/images/og/contactar-agencia-de-marketing-digital.jpg",
  "/nosotros": "/images/og/nosotros.jpg",
  "/blog": "/images/og/home.jpg",
  "/": "/images/og/home.jpg",
  "/casos-de-exito/soytechno-ecommerce-venezuela": "/images/og/casos-de-exito-soytechno-ecommerce-venezuela.jpg",
  "/casos-de-exito/jumex-shopify-dtc-ecommerce": "/images/og/casos-de-exito-jumex-shopify-dtc-ecommerce.jpg",
  "/casos-de-exito/odwalla-shopify-dtc-ecommerce": "/images/og/casos-de-exito-odwalla-shopify-dtc-ecommerce.jpg",
  "/agencia-e-commerce": "/images/og/agencia-e-commerce.jpg",
  "/agencia-seo": "/images/og/agencia-seo.jpg",
  "/agencia-sem": "/images/og/agencia-sem.jpg",
  "/agencia-diseno-web": "/images/og/agencia-diseno-web.jpg",
  "/casos-de-exito": "/images/og/casos-de-exito.jpg",
  "/blog/email-marketing/5-plataformas-para-email-marketing-efectivo": "/images/og/blog-email-marketing-5-plataformas-para-email-marketing-efectivo.jpg",
  "/blog/email-marketing/aprende-como-hacer-un-estrategia-digital-de-email-marketing": "/images/og/blog-email-marketing-aprende-como-hacer-un-estrategia-digital-de-email-marketing.jpg",
  "/blog/email-marketing/como-aprovechar-el-email-marketing-y-las-redes-sociales": "/images/og/blog-email-marketing-como-aprovechar-el-email-marketing-y-las-redes-sociales.jpg",
  "/blog/email-marketing/como-captar-clientes-potenciales": "/images/og/blog-email-marketing-como-captar-clientes-potenciales.jpg",
  "/blog/email-marketing/como-crear-una-base-de-datos-de-email-marketing": "/images/og/blog-email-marketing-como-crear-una-base-de-datos-de-email-marketing.jpg",
  "/blog/email-marketing/como-promocionar-en-black-friday-implementa-estas-estrategias": "/images/og/blog-email-marketing-como-promocionar-en-black-friday-implementa-estas-estrategi.jpg",
  "/blog/email-marketing/email-marketing-beneficio-que-te-generara-ingresos": "/images/og/blog-email-marketing-email-marketing-beneficio-que-te-generara-ingresos.jpg",
  "/blog/email-marketing/email-marketing-efectivo-que-todas-las-empresas-deben-usar": "/images/og/blog-email-marketing-email-marketing-efectivo-que-todas-las-empresas-deben-usar.jpg",
  "/blog/email-marketing/email-marketing-una-herramienta-que-no-puedes-dejar-de-usar-en-tu-empresa": "/images/og/blog-email-marketing-email-marketing-una-herramienta-que-no-puedes-dejar-de-usar.jpg",
  "/blog/email-marketing/estrategia-de-email-marketing": "/images/og/blog-email-marketing-estrategia-de-email-marketing.jpg",
  "/blog/email-marketing/haz-email-marketing-como-todo-un-experto-ejemplos": "/images/og/blog-email-marketing-haz-email-marketing-como-todo-un-experto-ejemplos.jpg",
  "/blog/email-marketing/seguir-los-reglamentos-te-hara-evitar-una-penalizacion": "/images/og/blog-email-marketing-seguir-los-reglamentos-te-hara-evitar-una-penalizacion.jpg",
  "/blog/mas-vistos/como-elegir-el-mejor-framework-para-tu-web": "/images/og/blog-mas-vistos-como-elegir-el-mejor-framework-para-tu-web.jpg",
  "/blog/mas-vistos/como-hacer-publicidad-en-instagram-en-el-2023": "/images/og/blog-mas-vistos-como-hacer-publicidad-en-instagram-en-el-2023.jpg",
  "/blog/mas-vistos/cual-es-la-mejor-hora-para-publicar-en-tiktok": "/images/og/blog-mas-vistos-cual-es-la-mejor-hora-para-publicar-en-tiktok.jpg",
  "/blog/mas-vistos/diseno-web-de-paginas-web": "/images/og/blog-mas-vistos-diseno-web-de-paginas-web.jpg",
  "/blog/mas-vistos/ecosistema-digital-de-tu-marca": "/images/og/blog-mas-vistos-ecosistema-digital-de-tu-marca.jpg",
  "/blog/mas-vistos/los-5-problemas-de-e-commerce": "/images/og/blog-mas-vistos-los-5-problemas-de-e-commerce.jpg",
  "/blog/mas-vistos/que-es-una-agencia-de-sem": "/images/og/blog-mas-vistos-que-es-una-agencia-de-sem.jpg",
  "/blog/mas-vistos/rediseno-web": "/images/og/blog-mas-vistos-rediseno-web.jpg",
  "/blog/mas-vistos/wireframe-conoce-ejemplos-tipos-y-herramientas-para-implementarlo": "/images/og/blog-mas-vistos-wireframe-conoce-ejemplos-tipos-y-herramientas-para-implementarl.jpg",
  "/blog/otros/como-posicionar-tu-negocio-en-google-ads": "/images/og/blog-otros-como-posicionar-tu-negocio-en-google-ads.jpg",
  "/blog/otros/conoce-todo-sobre-instagram-ads": "/images/og/blog-otros-conoce-todo-sobre-instagram-ads.jpg",
  "/blog/otros/descubre-por-que-debes-usar-whatsapp-business-en-tu-negocio": "/images/og/blog-otros-descubre-por-que-debes-usar-whatsapp-business-en-tu-negocio.jpg",
  "/blog/otros/el-gran-e-importante-big-data": "/images/og/blog-otros-el-gran-e-importante-big-data.jpg",
  "/blog/otros/es-tiktok-el-nuevo-google": "/images/og/blog-otros-es-tiktok-el-nuevo-google.jpg",
  "/blog/otros/estrategia-para-el-dia-de-las-madres": "/images/og/blog-otros-estrategia-para-el-dia-de-las-madres.jpg",
  "/blog/otros/impulsa-tu-negocio-con-una-escalera-de-valor": "/images/og/blog-otros-impulsa-tu-negocio-con-una-escalera-de-valor.jpg",
  "/blog/otros/por-que-debes-hacer-publicidad-digital-en-tu-negocio": "/images/og/blog-otros-por-que-debes-hacer-publicidad-digital-en-tu-negocio.jpg",
  "/blog/otros/tiktok-live-studio-la-forma-mas-facil-de-realizar-tu-directo": "/images/og/blog-otros-tiktok-live-studio-la-forma-mas-facil-de-realizar-tu-directo.jpg",
  "/blog/pautas-digitales/5-ventajas-para-obtener-clientes-con-facebook-ads": "/images/og/blog-pautas-digitales-5-ventajas-para-obtener-clientes-con-facebook-ads.jpg",
  "/blog/pautas-digitales/analitica-web-que-es-como-puede-ayudar-a-mi-marca": "/images/og/blog-pautas-digitales-analitica-web-que-es-como-puede-ayudar-a-mi-marca.jpg",
  "/blog/pautas-digitales/aprende-a-humanizar-la-marca-de-tu-negocio": "/images/og/blog-pautas-digitales-aprende-a-humanizar-la-marca-de-tu-negocio.jpg",
  "/blog/pautas-digitales/auditoria-de-instagram-potencia-tu-presencia-en-la-red-social": "/images/og/blog-pautas-digitales-auditoria-de-instagram-potencia-tu-presencia-en-la-red-soc.jpg",
  "/blog/pautas-digitales/como-crear-anuncios-en-facebook": "/images/og/blog-pautas-digitales-como-crear-anuncios-en-facebook.jpg",
  "/blog/pautas-digitales/como-crear-anuncios-en-instagram": "/images/og/blog-pautas-digitales-como-crear-anuncios-en-instagram.jpg",
  "/blog/pautas-digitales/como-usar-el-remarketing-para-tener-mas-clientes": "/images/og/blog-pautas-digitales-como-usar-el-remarketing-para-tener-mas-clientes.jpg",
  "/blog/pautas-digitales/como-usar-instagram-para-expandir-tu-negocio": "/images/og/blog-pautas-digitales-como-usar-instagram-para-expandir-tu-negocio.jpg",
  "/blog/pautas-digitales/conoce-como-impulsar-tu-marca-online": "/images/og/blog-pautas-digitales-conoce-como-impulsar-tu-marca-online.jpg",
  "/blog/pautas-digitales/conoce-los-tipos-de-marketing": "/images/og/blog-pautas-digitales-conoce-los-tipos-de-marketing.jpg",
  "/blog/pautas-digitales/conoce-todo-sobre-la-publicidad-en-redes-sociales": "/images/og/blog-pautas-digitales-conoce-todo-sobre-la-publicidad-en-redes-sociales.jpg",
  "/blog/pautas-digitales/consejos-para-que-hagas-pautas-en-tus-post-de-instagram": "/images/og/blog-pautas-digitales-consejos-para-que-hagas-pautas-en-tus-post-de-instagram.jpg",
  "/blog/pautas-digitales/criptomonedas-las-utilizarias-como-metodo-de-pago": "/images/og/blog-pautas-digitales-criptomonedas-las-utilizarias-como-metodo-de-pago.jpg",
  "/blog/pautas-digitales/descubre-todo-lo-que-el-posicionamiento-sem-tiene-para-ti": "/images/og/blog-pautas-digitales-descubre-todo-lo-que-el-posicionamiento-sem-tiene-para-ti.jpg",
  "/blog/pautas-digitales/el-pixel-de-facebook-y-como-te-ayuda-con-tus-campanas": "/images/og/blog-pautas-digitales-el-pixel-de-facebook-y-como-te-ayuda-con-tus-campanas.jpg",
  "/blog/pautas-digitales/el-sms-marketing": "/images/og/blog-pautas-digitales-el-sms-marketing.jpg",
  "/blog/pautas-digitales/errores-que-pueden-perjudicar-a-tu-marca-al-generar-anuncios-en-facebook": "/images/og/blog-pautas-digitales-errores-que-pueden-perjudicar-a-tu-marca-al-generar-anunci.jpg",
  "/blog/pautas-digitales/estrategias-de-marketing-digital-para-el-2022": "/images/og/blog-pautas-digitales-estrategias-de-marketing-digital-para-el-2022.jpg",
  "/blog/pautas-digitales/guia-para-hacer-marketing-digital": "/images/og/blog-pautas-digitales-guia-para-hacer-marketing-digital.jpg",
  "/blog/pautas-digitales/la-nueva-gestion-de-google-ads": "/images/og/blog-pautas-digitales-la-nueva-gestion-de-google-ads.jpg",
  "/blog/pautas-digitales/live-stream-shopping-compra-mientras-interactuas": "/images/og/blog-pautas-digitales-live-stream-shopping-compra-mientras-interactuas.jpg",
  "/blog/pautas-digitales/necesitas-realizar-un-informe-seo-nosotros-lo-hacemos-por-ti": "/images/og/blog-pautas-digitales-necesitas-realizar-un-informe-seo-nosotros-lo-hacemos-por-.jpg",
  "/blog/pautas-digitales/pasos-para-aumentar-clientes-en-tu-negocio": "/images/og/blog-pautas-digitales-pasos-para-aumentar-clientes-en-tu-negocio.jpg",
  "/blog/pautas-digitales/por-que-incluir-la-transformacion-digital-en-mi-negocio": "/images/og/blog-pautas-digitales-por-que-incluir-la-transformacion-digital-en-mi-negocio.jpg",
  "/blog/pautas-digitales/publicidad-digital-en-tu-negocio": "/images/og/blog-pautas-digitales-publicidad-digital-en-tu-negocio.jpg",
  "/blog/pautas-digitales/publicidad-navidena": "/images/og/blog-pautas-digitales-publicidad-navidena.jpg",
  "/blog/pautas-digitales/que-son-los-buyer-persona-y-como-se-determinan": "/images/og/blog-pautas-digitales-que-son-los-buyer-persona-y-como-se-determinan.jpg",
  "/blog/pautas-digitales/storytelling-en-el-marketing-digital": "/images/og/blog-pautas-digitales-storytelling-en-el-marketing-digital.jpg",
  "/blog/pautas-digitales/tiktok-ads-ahora-puedes-hacer-publicidad-en-tiktok": "/images/og/blog-pautas-digitales-tiktok-ads-ahora-puedes-hacer-publicidad-en-tiktok.jpg",
  "/blog/pautas-digitales/tipos-de-publicidad-online": "/images/og/blog-pautas-digitales-tipos-de-publicidad-online.jpg",
  "/blog/pautas-digitales/tipos-de-publicidad-online-conceptos-y-datos-curiosos": "/images/og/blog-pautas-digitales-tipos-de-publicidad-online-conceptos-y-datos-curiosos.jpg",
  "/blog/pautas-digitales/whatsapp-business": "/images/og/blog-pautas-digitales-whatsapp-business.jpg",
  "/blog/seo/6-herramientas-para-crear-informes-seo": "/images/og/blog-seo-6-herramientas-para-crear-informes-seo.jpg",
  "/blog/seo/7-consejos-seo-para-posicionar-tu-pagina": "/images/og/blog-seo-7-consejos-seo-para-posicionar-tu-pagina.jpg",
  "/blog/seo/aplicaciones-de-la-inteligencia-artificial": "/images/og/blog-seo-aplicaciones-de-la-inteligencia-artificial.jpg",
  "/blog/seo/aprende-todo-sobre-el-seo": "/images/og/blog-seo-aprende-todo-sobre-el-seo.jpg",
  "/blog/seo/auditoria-seo-que-es-como-se-hace": "/images/og/blog-seo-auditoria-seo-que-es-como-se-hace.jpg",
  "/blog/seo/blog-corporativo-aumenta-el-trafico-de-tu-sitio-web": "/images/og/blog-seo-blog-corporativo-aumenta-el-trafico-de-tu-sitio-web.jpg",
  "/blog/seo/chat-gpt-puede-mejorar-el-seo-de-una-pagina-web": "/images/og/blog-seo-chat-gpt-puede-mejorar-el-seo-de-una-pagina-web.jpg",
  "/blog/seo/como-elegir-tus-palabras-claves": "/images/og/blog-seo-como-elegir-tus-palabras-claves.jpg",
  "/blog/seo/como-hacer-posicionamiento-web-en-buscadores": "/images/og/blog-seo-como-hacer-posicionamiento-web-en-buscadores.jpg",
  "/blog/seo/como-verificar-la-veracidad-del-contenido-creado-con-herramientas-de-inteligencia-artificial": "/images/og/blog-seo-como-verificar-la-veracidad-del-contenido-creado-con-herramientas-de-in.jpg",
  "/blog/seo/conoce-los-tipos-de-enlaces-seo": "/images/og/blog-seo-conoce-los-tipos-de-enlaces-seo.jpg",
  "/blog/seo/consejos-para-la-optimizacion-web": "/images/og/blog-seo-consejos-para-la-optimizacion-web.jpg",
  "/blog/seo/contenido-duplicado": "/images/og/blog-seo-contenido-duplicado.jpg",
  "/blog/seo/desarrollo-ui-ux": "/images/og/blog-seo-desarrollo-ui-ux.jpg",
  "/blog/seo/diseno-web-y-posicionamiento-seo": "/images/og/blog-seo-diseno-web-y-posicionamiento-seo.jpg",
  "/blog/seo/ejemplos-de-marketing-de-contenido": "/images/og/blog-seo-ejemplos-de-marketing-de-contenido.jpg",
  "/blog/seo/google-y-su-inteligencia-artificial": "/images/og/blog-seo-google-y-su-inteligencia-artificial.jpg",
  "/blog/seo/metadescripcion-que-es": "/images/og/blog-seo-metadescripcion-que-es.jpg",
  "/blog/seo/optimizacion-multimedia": "/images/og/blog-seo-optimizacion-multimedia.jpg",
  "/blog/seo/posicionamiento-organico-vs-pago": "/images/og/blog-seo-posicionamiento-organico-vs-pago.jpg",
  "/blog/seo/que-es-data-studio-de-google-y-como-funciona": "/images/og/blog-seo-que-es-data-studio-de-google-y-como-funciona.jpg",
  "/blog/seo/que-es-la-intencion-de-busqueda-y-cuales-son-sus-beneficios": "/images/og/blog-seo-que-es-la-intencion-de-busqueda-y-cuales-son-sus-beneficios.jpg",
  "/blog/seo/que-es-un-blog": "/images/og/blog-seo-que-es-un-blog.jpg",
  "/blog/seo/rich-snippet-ayuda-a-optimizar-tu-web": "/images/og/blog-seo-rich-snippet-ayuda-a-optimizar-tu-web.jpg",
  "/blog/seo/seo-y-sem-que-son-y-en-que-se-diferencian": "/images/og/blog-seo-seo-y-sem-que-son-y-en-que-se-diferencian.jpg",
  "/blog/seo/tendencias-seo-2020": "/images/og/blog-seo-tendencias-seo-2020.jpg",
  "/blog/seo/todo-sobre-el-seo": "/images/og/blog-seo-todo-sobre-el-seo.jpg",
  "/blog/seo/web-app-y-app-nativa-cual-es-la-mejor-opcion": "/images/og/blog-seo-web-app-y-app-nativa-cual-es-la-mejor-opcion.jpg",
  "/blog/tecnologia/actualizar-tu-e-commerce": "/images/og/blog-tecnologia-actualizar-tu-e-commerce.jpg",
  "/blog/tecnologia/agencia-seo-internacional-en-el-2025-es-una-necesidad": "/images/og/blog-tecnologia-agencia-seo-internacional-en-el-2025-es-una-necesidad.jpg",
  "/blog/tecnologia/chatbot-inteligencia-artificial-personalizada-para-tu-activo-digital": "/images/og/blog-tecnologia-chatbot-inteligencia-artificial-personalizada-para-tu-activo-dig.jpg",
  "/blog/tecnologia/cintillos-de-promocion": "/images/og/blog-tecnologia-cintillos-de-promocion.jpg",
  "/blog/tecnologia/como-crear-un-chatbot-para-tu-empresa-en-5-minutos": "/images/og/blog-tecnologia-como-crear-un-chatbot-para-tu-empresa-en-5-minutos.jpg",
  "/blog/tecnologia/crear-un-e-commerce": "/images/og/blog-tecnologia-crear-un-e-commerce.jpg",
  "/blog/tecnologia/desarrollo-de-aplicaciones-web": "/images/og/blog-tecnologia-desarrollo-de-aplicaciones-web.jpg",
  "/blog/tecnologia/ecommerce-mi-negocio-online": "/images/og/blog-tecnologia-ecommerce-mi-negocio-online.jpg",
  "/blog/tecnologia/programacion-web-que-es-como-puede-servirle-a-mi-marca": "/images/og/blog-tecnologia-programacion-web-que-es-como-puede-servirle-a-mi-marca.jpg",
  "/blog/tecnologia/que-es-wix": "/images/og/blog-tecnologia-que-es-wix.jpg",
  "/blog/tecnologia/que-es-wordpress-por-que-tengo-que-usarlo": "/images/og/blog-tecnologia-que-es-wordpress-por-que-tengo-que-usarlo.jpg",
  "/blog/tecnologia/tendencias-en-diseno-web-para-el-2022": "/images/og/blog-tecnologia-tendencias-en-diseno-web-para-el-2022.jpg",
  "/blog/tecnologia/zelle-en-venezuela-un-metodo-de-pago-para-tu-ecommerce": "/images/og/blog-tecnologia-zelle-en-venezuela-un-metodo-de-pago-para-tu-ecommerce.jpg"
} as const;

export const OG_JPEG_BY_BLOG_SLUG = {
  "5-plataformas-para-email-marketing-efectivo": "/images/og/blog-email-marketing-5-plataformas-para-email-marketing-efectivo.jpg",
  "aprende-como-hacer-un-estrategia-digital-de-email-marketing": "/images/og/blog-email-marketing-aprende-como-hacer-un-estrategia-digital-de-email-marketing.jpg",
  "como-aprovechar-el-email-marketing-y-las-redes-sociales": "/images/og/blog-email-marketing-como-aprovechar-el-email-marketing-y-las-redes-sociales.jpg",
  "como-captar-clientes-potenciales": "/images/og/blog-email-marketing-como-captar-clientes-potenciales.jpg",
  "como-crear-una-base-de-datos-de-email-marketing": "/images/og/blog-email-marketing-como-crear-una-base-de-datos-de-email-marketing.jpg",
  "como-promocionar-en-black-friday-implementa-estas-estrategias": "/images/og/blog-email-marketing-como-promocionar-en-black-friday-implementa-estas-estrategi.jpg",
  "email-marketing-beneficio-que-te-generara-ingresos": "/images/og/blog-email-marketing-email-marketing-beneficio-que-te-generara-ingresos.jpg",
  "email-marketing-efectivo-que-todas-las-empresas-deben-usar": "/images/og/blog-email-marketing-email-marketing-efectivo-que-todas-las-empresas-deben-usar.jpg",
  "email-marketing-una-herramienta-que-no-puedes-dejar-de-usar-en-tu-empresa": "/images/og/blog-email-marketing-email-marketing-una-herramienta-que-no-puedes-dejar-de-usar.jpg",
  "estrategia-de-email-marketing": "/images/og/blog-email-marketing-estrategia-de-email-marketing.jpg",
  "haz-email-marketing-como-todo-un-experto-ejemplos": "/images/og/blog-email-marketing-haz-email-marketing-como-todo-un-experto-ejemplos.jpg",
  "seguir-los-reglamentos-te-hara-evitar-una-penalizacion": "/images/og/blog-email-marketing-seguir-los-reglamentos-te-hara-evitar-una-penalizacion.jpg",
  "como-elegir-el-mejor-framework-para-tu-web": "/images/og/blog-mas-vistos-como-elegir-el-mejor-framework-para-tu-web.jpg",
  "como-hacer-publicidad-en-instagram-en-el-2023": "/images/og/blog-mas-vistos-como-hacer-publicidad-en-instagram-en-el-2023.jpg",
  "cual-es-la-mejor-hora-para-publicar-en-tiktok": "/images/og/blog-mas-vistos-cual-es-la-mejor-hora-para-publicar-en-tiktok.jpg",
  "diseno-web-de-paginas-web": "/images/og/blog-mas-vistos-diseno-web-de-paginas-web.jpg",
  "ecosistema-digital-de-tu-marca": "/images/og/blog-mas-vistos-ecosistema-digital-de-tu-marca.jpg",
  "los-5-problemas-de-e-commerce": "/images/og/blog-mas-vistos-los-5-problemas-de-e-commerce.jpg",
  "que-es-una-agencia-de-sem": "/images/og/blog-mas-vistos-que-es-una-agencia-de-sem.jpg",
  "rediseno-web": "/images/og/blog-mas-vistos-rediseno-web.jpg",
  "wireframe-conoce-ejemplos-tipos-y-herramientas-para-implementarlo": "/images/og/blog-mas-vistos-wireframe-conoce-ejemplos-tipos-y-herramientas-para-implementarl.jpg",
  "como-posicionar-tu-negocio-en-google-ads": "/images/og/blog-otros-como-posicionar-tu-negocio-en-google-ads.jpg",
  "conoce-todo-sobre-instagram-ads": "/images/og/blog-otros-conoce-todo-sobre-instagram-ads.jpg",
  "descubre-por-que-debes-usar-whatsapp-business-en-tu-negocio": "/images/og/blog-otros-descubre-por-que-debes-usar-whatsapp-business-en-tu-negocio.jpg",
  "el-gran-e-importante-big-data": "/images/og/blog-otros-el-gran-e-importante-big-data.jpg",
  "es-tiktok-el-nuevo-google": "/images/og/blog-otros-es-tiktok-el-nuevo-google.jpg",
  "estrategia-para-el-dia-de-las-madres": "/images/og/blog-otros-estrategia-para-el-dia-de-las-madres.jpg",
  "impulsa-tu-negocio-con-una-escalera-de-valor": "/images/og/blog-otros-impulsa-tu-negocio-con-una-escalera-de-valor.jpg",
  "por-que-debes-hacer-publicidad-digital-en-tu-negocio": "/images/og/blog-otros-por-que-debes-hacer-publicidad-digital-en-tu-negocio.jpg",
  "tiktok-live-studio-la-forma-mas-facil-de-realizar-tu-directo": "/images/og/blog-otros-tiktok-live-studio-la-forma-mas-facil-de-realizar-tu-directo.jpg",
  "5-ventajas-para-obtener-clientes-con-facebook-ads": "/images/og/blog-pautas-digitales-5-ventajas-para-obtener-clientes-con-facebook-ads.jpg",
  "analitica-web-que-es-como-puede-ayudar-a-mi-marca": "/images/og/blog-pautas-digitales-analitica-web-que-es-como-puede-ayudar-a-mi-marca.jpg",
  "aprende-a-humanizar-la-marca-de-tu-negocio": "/images/og/blog-pautas-digitales-aprende-a-humanizar-la-marca-de-tu-negocio.jpg",
  "auditoria-de-instagram-potencia-tu-presencia-en-la-red-social": "/images/og/blog-pautas-digitales-auditoria-de-instagram-potencia-tu-presencia-en-la-red-soc.jpg",
  "como-crear-anuncios-en-facebook": "/images/og/blog-pautas-digitales-como-crear-anuncios-en-facebook.jpg",
  "como-crear-anuncios-en-instagram": "/images/og/blog-pautas-digitales-como-crear-anuncios-en-instagram.jpg",
  "como-usar-el-remarketing-para-tener-mas-clientes": "/images/og/blog-pautas-digitales-como-usar-el-remarketing-para-tener-mas-clientes.jpg",
  "como-usar-instagram-para-expandir-tu-negocio": "/images/og/blog-pautas-digitales-como-usar-instagram-para-expandir-tu-negocio.jpg",
  "conoce-como-impulsar-tu-marca-online": "/images/og/blog-pautas-digitales-conoce-como-impulsar-tu-marca-online.jpg",
  "conoce-los-tipos-de-marketing": "/images/og/blog-pautas-digitales-conoce-los-tipos-de-marketing.jpg",
  "conoce-todo-sobre-la-publicidad-en-redes-sociales": "/images/og/blog-pautas-digitales-conoce-todo-sobre-la-publicidad-en-redes-sociales.jpg",
  "consejos-para-que-hagas-pautas-en-tus-post-de-instagram": "/images/og/blog-pautas-digitales-consejos-para-que-hagas-pautas-en-tus-post-de-instagram.jpg",
  "criptomonedas-las-utilizarias-como-metodo-de-pago": "/images/og/blog-pautas-digitales-criptomonedas-las-utilizarias-como-metodo-de-pago.jpg",
  "descubre-todo-lo-que-el-posicionamiento-sem-tiene-para-ti": "/images/og/blog-pautas-digitales-descubre-todo-lo-que-el-posicionamiento-sem-tiene-para-ti.jpg",
  "el-pixel-de-facebook-y-como-te-ayuda-con-tus-campanas": "/images/og/blog-pautas-digitales-el-pixel-de-facebook-y-como-te-ayuda-con-tus-campanas.jpg",
  "el-sms-marketing": "/images/og/blog-pautas-digitales-el-sms-marketing.jpg",
  "errores-que-pueden-perjudicar-a-tu-marca-al-generar-anuncios-en-facebook": "/images/og/blog-pautas-digitales-errores-que-pueden-perjudicar-a-tu-marca-al-generar-anunci.jpg",
  "estrategias-de-marketing-digital-para-el-2022": "/images/og/blog-pautas-digitales-estrategias-de-marketing-digital-para-el-2022.jpg",
  "guia-para-hacer-marketing-digital": "/images/og/blog-pautas-digitales-guia-para-hacer-marketing-digital.jpg",
  "la-nueva-gestion-de-google-ads": "/images/og/blog-pautas-digitales-la-nueva-gestion-de-google-ads.jpg",
  "live-stream-shopping-compra-mientras-interactuas": "/images/og/blog-pautas-digitales-live-stream-shopping-compra-mientras-interactuas.jpg",
  "necesitas-realizar-un-informe-seo-nosotros-lo-hacemos-por-ti": "/images/og/blog-pautas-digitales-necesitas-realizar-un-informe-seo-nosotros-lo-hacemos-por-.jpg",
  "pasos-para-aumentar-clientes-en-tu-negocio": "/images/og/blog-pautas-digitales-pasos-para-aumentar-clientes-en-tu-negocio.jpg",
  "por-que-incluir-la-transformacion-digital-en-mi-negocio": "/images/og/blog-pautas-digitales-por-que-incluir-la-transformacion-digital-en-mi-negocio.jpg",
  "publicidad-digital-en-tu-negocio": "/images/og/blog-pautas-digitales-publicidad-digital-en-tu-negocio.jpg",
  "publicidad-navidena": "/images/og/blog-pautas-digitales-publicidad-navidena.jpg",
  "que-son-los-buyer-persona-y-como-se-determinan": "/images/og/blog-pautas-digitales-que-son-los-buyer-persona-y-como-se-determinan.jpg",
  "storytelling-en-el-marketing-digital": "/images/og/blog-pautas-digitales-storytelling-en-el-marketing-digital.jpg",
  "tiktok-ads-ahora-puedes-hacer-publicidad-en-tiktok": "/images/og/blog-pautas-digitales-tiktok-ads-ahora-puedes-hacer-publicidad-en-tiktok.jpg",
  "tipos-de-publicidad-online": "/images/og/blog-pautas-digitales-tipos-de-publicidad-online.jpg",
  "tipos-de-publicidad-online-conceptos-y-datos-curiosos": "/images/og/blog-pautas-digitales-tipos-de-publicidad-online-conceptos-y-datos-curiosos.jpg",
  "whatsapp-business": "/images/og/blog-pautas-digitales-whatsapp-business.jpg",
  "6-herramientas-para-crear-informes-seo": "/images/og/blog-seo-6-herramientas-para-crear-informes-seo.jpg",
  "7-consejos-seo-para-posicionar-tu-pagina": "/images/og/blog-seo-7-consejos-seo-para-posicionar-tu-pagina.jpg",
  "aplicaciones-de-la-inteligencia-artificial": "/images/og/blog-seo-aplicaciones-de-la-inteligencia-artificial.jpg",
  "aprende-todo-sobre-el-seo": "/images/og/blog-seo-aprende-todo-sobre-el-seo.jpg",
  "auditoria-seo-que-es-como-se-hace": "/images/og/blog-seo-auditoria-seo-que-es-como-se-hace.jpg",
  "blog-corporativo-aumenta-el-trafico-de-tu-sitio-web": "/images/og/blog-seo-blog-corporativo-aumenta-el-trafico-de-tu-sitio-web.jpg",
  "chat-gpt-puede-mejorar-el-seo-de-una-pagina-web": "/images/og/blog-seo-chat-gpt-puede-mejorar-el-seo-de-una-pagina-web.jpg",
  "como-elegir-tus-palabras-claves": "/images/og/blog-seo-como-elegir-tus-palabras-claves.jpg",
  "como-hacer-posicionamiento-web-en-buscadores": "/images/og/blog-seo-como-hacer-posicionamiento-web-en-buscadores.jpg",
  "como-verificar-la-veracidad-del-contenido-creado-con-herramientas-de-inteligencia-artificial": "/images/og/blog-seo-como-verificar-la-veracidad-del-contenido-creado-con-herramientas-de-in.jpg",
  "conoce-los-tipos-de-enlaces-seo": "/images/og/blog-seo-conoce-los-tipos-de-enlaces-seo.jpg",
  "consejos-para-la-optimizacion-web": "/images/og/blog-seo-consejos-para-la-optimizacion-web.jpg",
  "contenido-duplicado": "/images/og/blog-seo-contenido-duplicado.jpg",
  "desarrollo-ui-ux": "/images/og/blog-seo-desarrollo-ui-ux.jpg",
  "diseno-web-y-posicionamiento-seo": "/images/og/blog-seo-diseno-web-y-posicionamiento-seo.jpg",
  "ejemplos-de-marketing-de-contenido": "/images/og/blog-seo-ejemplos-de-marketing-de-contenido.jpg",
  "google-y-su-inteligencia-artificial": "/images/og/blog-seo-google-y-su-inteligencia-artificial.jpg",
  "metadescripcion-que-es": "/images/og/blog-seo-metadescripcion-que-es.jpg",
  "optimizacion-multimedia": "/images/og/blog-seo-optimizacion-multimedia.jpg",
  "posicionamiento-organico-vs-pago": "/images/og/blog-seo-posicionamiento-organico-vs-pago.jpg",
  "que-es-data-studio-de-google-y-como-funciona": "/images/og/blog-seo-que-es-data-studio-de-google-y-como-funciona.jpg",
  "que-es-la-intencion-de-busqueda-y-cuales-son-sus-beneficios": "/images/og/blog-seo-que-es-la-intencion-de-busqueda-y-cuales-son-sus-beneficios.jpg",
  "que-es-un-blog": "/images/og/blog-seo-que-es-un-blog.jpg",
  "rich-snippet-ayuda-a-optimizar-tu-web": "/images/og/blog-seo-rich-snippet-ayuda-a-optimizar-tu-web.jpg",
  "seo-y-sem-que-son-y-en-que-se-diferencian": "/images/og/blog-seo-seo-y-sem-que-son-y-en-que-se-diferencian.jpg",
  "tendencias-seo-2020": "/images/og/blog-seo-tendencias-seo-2020.jpg",
  "todo-sobre-el-seo": "/images/og/blog-seo-todo-sobre-el-seo.jpg",
  "web-app-y-app-nativa-cual-es-la-mejor-opcion": "/images/og/blog-seo-web-app-y-app-nativa-cual-es-la-mejor-opcion.jpg",
  "actualizar-tu-e-commerce": "/images/og/blog-tecnologia-actualizar-tu-e-commerce.jpg",
  "agencia-seo-internacional-en-el-2025-es-una-necesidad": "/images/og/blog-tecnologia-agencia-seo-internacional-en-el-2025-es-una-necesidad.jpg",
  "chatbot-inteligencia-artificial-personalizada-para-tu-activo-digital": "/images/og/blog-tecnologia-chatbot-inteligencia-artificial-personalizada-para-tu-activo-dig.jpg",
  "cintillos-de-promocion": "/images/og/blog-tecnologia-cintillos-de-promocion.jpg",
  "como-crear-un-chatbot-para-tu-empresa-en-5-minutos": "/images/og/blog-tecnologia-como-crear-un-chatbot-para-tu-empresa-en-5-minutos.jpg",
  "crear-un-e-commerce": "/images/og/blog-tecnologia-crear-un-e-commerce.jpg",
  "desarrollo-de-aplicaciones-web": "/images/og/blog-tecnologia-desarrollo-de-aplicaciones-web.jpg",
  "ecommerce-mi-negocio-online": "/images/og/blog-tecnologia-ecommerce-mi-negocio-online.jpg",
  "programacion-web-que-es-como-puede-servirle-a-mi-marca": "/images/og/blog-tecnologia-programacion-web-que-es-como-puede-servirle-a-mi-marca.jpg",
  "que-es-wix": "/images/og/blog-tecnologia-que-es-wix.jpg",
  "que-es-wordpress-por-que-tengo-que-usarlo": "/images/og/blog-tecnologia-que-es-wordpress-por-que-tengo-que-usarlo.jpg",
  "tendencias-en-diseno-web-para-el-2022": "/images/og/blog-tecnologia-tendencias-en-diseno-web-para-el-2022.jpg",
  "zelle-en-venezuela-un-metodo-de-pago-para-tu-ecommerce": "/images/og/blog-tecnologia-zelle-en-venezuela-un-metodo-de-pago-para-tu-ecommerce.jpg"
} as const;

export type OgPath = keyof typeof OG_JPEG_BY_PATH;
export type OgBlogSlug = keyof typeof OG_JPEG_BY_BLOG_SLUG;

export function ogJpegForPath(pathname: string | undefined | null): string {
  if (!pathname) return '';
  const clean = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  return OG_JPEG_BY_PATH[clean as OgPath] || '';
}

export function ogJpegForBlogSlug(slug: string | undefined | null): string {
  if (!slug) return '';
  return OG_JPEG_BY_BLOG_SLUG[slug as OgBlogSlug] || '';
}

export function ogJpegMeta(url: string, alt = 'Playful Agency') {
  return { url, width: OG_JPEG_SIZE.width, height: OG_JPEG_SIZE.height, alt };
}
