import { isClosedBlogPath } from './blog-closed-paths.ts';

const SITEMAP_ORIGIN = 'https://playfulagency.com';

export const SITEMAP_STATIC_PATHS = [
  "/",
  "/nosotros",
  "/contactar-agencia-de-marketing-digital",
  "/agencia-e-commerce",
  "/agencia-shopify",
  "/agencia-seo",
  "/agencia-sem",
  "/agencia-diseno-web",
  "/casos-de-exito-agencia-de-marketing-digital",
  "/casos-de-exito/jumex-shopify-dtc-ecommerce",
  "/casos-de-exito/odwalla-shopify-dtc-ecommerce",
  "/blog",
  "/politica-de-privacidad",
] as const;

export const SITEMAP_BLOG_PATHS = [
  "/blog/email-marketing/5-plataformas-para-email-marketing-efectivo",
  "/blog/email-marketing/aprende-como-hacer-un-estrategia-digital-de-email-marketing",
  "/blog/email-marketing/como-aprovechar-el-email-marketing-y-las-redes-sociales",
  "/blog/email-marketing/como-captar-clientes-potenciales",
  "/blog/email-marketing/como-crear-una-base-de-datos-de-email-marketing",
  "/blog/email-marketing/como-hacer-un-email-marketing-eficaz-durante-la-pandemia",
  "/blog/email-marketing/como-promocionar-en-black-friday-implementa-estas-estrategias",
  "/blog/email-marketing/email-marketing-beneficio-que-te-generara-ingresos",
  "/blog/email-marketing/email-marketing-efectivo-que-todas-las-empresas-deben-usar",
  "/blog/email-marketing/email-marketing-una-herramienta-que-no-puedes-dejar-de-usar-en-tu-empresa",
  "/blog/email-marketing/estrategia-de-email-marketing",
  "/blog/email-marketing/haz-email-marketing-como-todo-un-experto-ejemplos",
  "/blog/email-marketing/seguir-los-reglamentos-te-hara-evitar-una-penalizacion",
  "/blog/mas-vistos/bad-bunny-como-marca-la-potencia-del-marketing-musical",
  "/blog/mas-vistos/como-elegir-el-mejor-framework-para-tu-web",
  "/blog/mas-vistos/como-hacer-publicidad-en-instagram-en-el-2023",
  "/blog/mas-vistos/cual-es-la-mejor-hora-para-publicar-en-tiktok",
  "/blog/mas-vistos/diseno-web-de-paginas-web",
  "/blog/mas-vistos/ecosistema-digital-de-tu-marca",
  "/blog/mas-vistos/los-5-problemas-de-e-commerce",
  "/blog/mas-vistos/marketing-deportivo-qatar-2022",
  "/blog/mas-vistos/messi-y-el-marketing-hablemos-sobre-su-marca-personal",
  "/blog/mas-vistos/que-es-una-agencia-de-sem",
  "/blog/mas-vistos/quiero-ver-mi-negocio-en-google-maps",
  "/blog/mas-vistos/rediseno-web",
  "/blog/mas-vistos/shakira-y-pique-un-buen-ejemplo-del-marketing-emocional",
  "/blog/mas-vistos/todo-lo-que-debes-saber-para-ganar-dinero-con-tiktok",
  "/blog/mas-vistos/wireframe-conoce-ejemplos-tipos-y-herramientas-para-implementarlo",
  "/blog/otros/como-posicionar-tu-negocio-en-google-ads",
  "/blog/otros/conoce-todo-sobre-instagram-ads",
  "/blog/otros/debes-usar-el-lenguaje-inclusivo-en-redes-sociales",
  "/blog/otros/descubre-por-que-debes-usar-whatsapp-business-en-tu-negocio",
  "/blog/otros/el-gran-e-importante-big-data",
  "/blog/otros/es-tiktok-el-nuevo-google",
  "/blog/otros/estrategia-para-el-dia-de-las-madres",
  "/blog/otros/ibai-llanos-por-que-es-tendencia-y-que-tiene-que-ver-con-el-futbol",
  "/blog/otros/impulsa-tu-negocio-con-una-escalera-de-valor",
  "/blog/otros/lgbtq-siglas-con-historia-significado-y-marketing-de-inclusion",
  "/blog/otros/marketing-de-guerrilla-te-atreves-a-intentarlo",
  "/blog/otros/marketing-para-medicos-como-ganar-mientras-ayudas",
  "/blog/otros/mes-del-orgullo-gay-por-que-se-celebra",
  "/blog/otros/metaverso-que-es",
  "/blog/otros/por-que-debes-hacer-publicidad-digital-en-tu-negocio",
  "/blog/otros/tiktok-live-studio-la-forma-mas-facil-de-realizar-tu-directo",
  "/blog/otros/una-herramienta-para-ganar-autoridad",
  "/blog/otros/ya-sabes-cuando-se-celebra-el-dia-mundial-del-emoji",
  "/blog/pautas-digitales/5-ventajas-para-obtener-clientes-con-facebook-ads",
  "/blog/pautas-digitales/actualizaciones-de-instagram",
  "/blog/pautas-digitales/analitica-web-que-es-como-puede-ayudar-a-mi-marca",
  "/blog/pautas-digitales/anuncios-en-linkedin",
  "/blog/pautas-digitales/aprende-a-humanizar-la-marca-de-tu-negocio",
  "/blog/pautas-digitales/auditoria-de-instagram-potencia-tu-presencia-en-la-red-social",
  "/blog/pautas-digitales/como-crear-anuncios-en-facebook",
  "/blog/pautas-digitales/como-crear-anuncios-en-instagram",
  "/blog/pautas-digitales/como-ser-tendencia",
  "/blog/pautas-digitales/como-usar-el-remarketing-para-tener-mas-clientes",
  "/blog/pautas-digitales/como-usar-instagram-para-expandir-tu-negocio",
  "/blog/pautas-digitales/conoce-como-impulsar-tu-marca-online",
  "/blog/pautas-digitales/conoce-el-marketing-digital-del-2020",
  "/blog/pautas-digitales/conoce-los-tipos-de-marketing",
  "/blog/pautas-digitales/conoce-todo-sobre-la-publicidad-en-redes-sociales",
  "/blog/pautas-digitales/consejos-para-que-hagas-pautas-en-tus-post-de-instagram",
  "/blog/pautas-digitales/convierte-en-el-experto-de-los-webinar",
  "/blog/pautas-digitales/criptomonedas-las-utilizarias-como-metodo-de-pago",
  "/blog/pautas-digitales/descubre-todo-lo-que-el-posicionamiento-sem-tiene-para-ti",
  "/blog/pautas-digitales/el-pixel-de-facebook-y-como-te-ayuda-con-tus-campanas",
  "/blog/pautas-digitales/el-sms-marketing",
  "/blog/pautas-digitales/errores-que-pueden-perjudicar-a-tu-marca-al-generar-anuncios-en-facebook",
  "/blog/pautas-digitales/estrategias-de-marketing-digital-para-el-2022",
  "/blog/pautas-digitales/google-grants-descubre-que-es-y-como-funciona",
  "/blog/pautas-digitales/guia-para-hacer-marketing-digital",
  "/blog/pautas-digitales/la-nueva-gestion-de-google-ads",
  "/blog/pautas-digitales/linkedin-ads-aumenta-el-alcance-de-tu-negocio",
  "/blog/pautas-digitales/live-stream-shopping-compra-mientras-interactuas",
  "/blog/pautas-digitales/necesitas-realizar-un-informe-seo-nosotros-lo-hacemos-por-ti",
  "/blog/pautas-digitales/pasos-para-aumentar-clientes-en-tu-negocio",
  "/blog/pautas-digitales/por-que-incluir-la-transformacion-digital-en-mi-negocio",
  "/blog/pautas-digitales/porque-tener-un-perfil-empresarial-en-linkedin",
  "/blog/pautas-digitales/publicidad-digital-en-tu-negocio",
  "/blog/pautas-digitales/publicidad-navidena",
  "/blog/pautas-digitales/que-son-los-buyer-persona-y-como-se-determinan",
  "/blog/pautas-digitales/storytelling-en-el-marketing-digital",
  "/blog/pautas-digitales/tiktok-ads-ahora-puedes-hacer-publicidad-en-tiktok",
  "/blog/pautas-digitales/tipos-de-publicidad-online",
  "/blog/pautas-digitales/tipos-de-publicidad-online-conceptos-y-datos-curiosos",
  "/blog/pautas-digitales/twitter-ads",
  "/blog/pautas-digitales/whatsapp-business",
  "/blog/seo/6-herramientas-para-crear-informes-seo",
  "/blog/seo/7-consejos-seo-para-posicionar-tu-pagina",
  "/blog/seo/aplicaciones-de-la-inteligencia-artificial",
  "/blog/seo/aprende-todo-sobre-el-seo",
  "/blog/seo/auditoria-seo-que-es-como-se-hace",
  "/blog/seo/black-hat-seo",
  "/blog/seo/blog-corporativo-aumenta-el-trafico-de-tu-sitio-web",
  "/blog/seo/busqueda-por-voz-que-es-y-como-afecta-al-seo",
  "/blog/seo/chat-gpt-puede-mejorar-el-seo-de-una-pagina-web",
  "/blog/seo/como-elegir-tus-palabras-claves",
  "/blog/seo/como-hacer-posicionamiento-web-en-buscadores",
  "/blog/seo/como-verificar-la-veracidad-del-contenido-creado-con-herramientas-de-inteligencia-artificial",
  "/blog/seo/conoce-los-tipos-de-enlaces-seo",
  "/blog/seo/consejos-para-la-optimizacion-web",
  "/blog/seo/contenido-duplicado",
  "/blog/seo/desarrollo-ui-ux",
  "/blog/seo/diseno-web-y-posicionamiento-seo",
  "/blog/seo/ejemplos-de-marketing-de-contenido",
  "/blog/seo/google-y-su-inteligencia-artificial",
  "/blog/seo/hacks-seo-local",
  "/blog/seo/marketing-social-la-estrategia-ganadora-de-las-ong",
  "/blog/seo/metadescripcion-que-es",
  "/blog/seo/optimizacion-multimedia",
  "/blog/seo/posicionamiento-organico-vs-pago",
  "/blog/seo/que-es-data-studio-de-google-y-como-funciona",
  "/blog/seo/que-es-la-intencion-de-busqueda-y-cuales-son-sus-beneficios",
  "/blog/seo/que-es-un-blog",
  "/blog/seo/rich-snippet-ayuda-a-optimizar-tu-web",
  "/blog/seo/seo-y-sem-que-son-y-en-que-se-diferencian",
  "/blog/seo/tendencias-seo-2020",
  "/blog/seo/todo-sobre-el-seo",
  "/blog/seo/web-app-y-app-nativa-cual-es-la-mejor-opcion",
  "/blog/tecnologia/actualizar-tu-e-commerce",
  "/blog/tecnologia/agencia-seo-internacional-en-el-2025-es-una-necesidad",
  "/blog/tecnologia/chatbot-inteligencia-artificial-personalizada-para-tu-activo-digital",
  "/blog/tecnologia/cintillos-de-promocion",
  "/blog/tecnologia/como-crear-un-chatbot-para-tu-empresa-en-5-minutos",
  "/blog/tecnologia/crear-un-e-commerce",
  "/blog/tecnologia/desarrollo-de-aplicaciones-web",
  "/blog/tecnologia/ecommerce-mi-negocio-online",
  "/blog/tecnologia/google-ads-grants-con-un-blog-digital",
  "/blog/tecnologia/lenguajes-de-programacion-para-que-sirve-y-cuales-son-los-mas-usados",
  "/blog/tecnologia/programacion-web-que-es-como-puede-servirle-a-mi-marca",
  "/blog/tecnologia/que-es-wix",
  "/blog/tecnologia/que-es-wordpress-por-que-tengo-que-usarlo",
  "/blog/tecnologia/tendencias-en-diseno-web-para-el-2022",
  "/blog/tecnologia/zelle-en-venezuela-un-metodo-de-pago-para-tu-ecommerce",
] as const;

export function getSitemapPaths(): string[] {
  return [
    ...SITEMAP_STATIC_PATHS,
    ...SITEMAP_BLOG_PATHS.filter((path) => !isClosedBlogPath(path)),
  ];
}

export function getSitemapLocs(): string[] {
  return getSitemapPaths().map((path) => (
    path === '/' ? `${SITEMAP_ORIGIN}/` : `${SITEMAP_ORIGIN}${path}`
  ));
}

export function buildSitemapXml(): string {
  const urls = getSitemapLocs().map((loc) => `  <url><loc>${loc}</loc></url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}
